spring:
  application:
    name: itprom
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081
springdoc:
  swagger-ui:
    path: /itprom-api.html
    operations-sorter: method